manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: microros
      url-base: https://github.com/micro-ROS
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import:
        path: west.yml
    - name: micro_ros_zephyr_module
      remote: microros
      revision: kilted
      path: modules/libmicroros
  self:
    path: app
